"""SQLAlchemy models (spec section 23).

Two conventions run through the whole schema:

* **Vocabularies are ``VARCHAR`` with a ``CHECK`` constraint generated from
  ``packages/shared-types/enums.json``, not native PostgreSQL ``ENUM`` types.** Native
  enums require a migration and a table rewrite to add a value, which is exactly the kind
  of friction that leads to a hard-coded string sneaking in somewhere. A check constraint
  is regenerated from the shared file, and ``tests/test_vocab_parity.py`` fails if the
  database and the shared vocabulary disagree.

* **Provenance is not optional.** Anything derived from an external source carries its
  source, licence and acquisition time; anything generated by a model carries provider,
  model, prompt version and input hash (spec sections 21 and 23).
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import Any

from sqlalchemy import (
    JSON,
    BigInteger,
    Boolean,
    CheckConstraint,
    DateTime,
    Float,
    ForeignKey,
    Index,
    Integer,
    Sequence,
    String,
    Text,
    UniqueConstraint,
    func,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship

from papermatch_api import vocab

#: JSONB on PostgreSQL, plain JSON elsewhere, so unit tests can use SQLite.
JsonType = JSON().with_variant(JSONB(), "postgresql")
UuidType = UUID(as_uuid=True).with_variant(String(36), "sqlite")


class Base(DeclarativeBase):
    pass


def _uuid() -> uuid.UUID:
    return uuid.uuid4()


def vocab_check(column_name: str, vocabulary_key: str) -> CheckConstraint:
    """CHECK constraint listing every value of a shared vocabulary."""
    allowed = ", ".join(f"'{value}'" for value in vocab.values(vocabulary_key))
    return CheckConstraint(
        f"{column_name} IN ({allowed})",
        name=f"ck_{column_name}_{vocabulary_key.lower()}",
    )


class TimestampMixin:
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False
    )


# --------------------------------------------------------------------------- users


class User(Base, TimestampMixin):
    __tablename__ = "users"

    id: Mapped[uuid.UUID] = mapped_column(UuidType, primary_key=True, default=_uuid)
    is_guest: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)
    email: Mapped[str | None] = mapped_column(String(320), unique=True, nullable=True)
    display_name: Mapped[str | None] = mapped_column(String(120), nullable=True)
    onboarding_completed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    settings: Mapped[UserSettings] = relationship(
        back_populates="user", uselist=False, cascade="all, delete-orphan"
    )
    interests: Mapped[list[Interest]] = relationship(
        back_populates="user", cascade="all, delete-orphan"
    )


class UserSettings(Base, TimestampMixin):
    """Spec sections 18 and 20. Accessibility settings live here, not in client storage,
    so they follow the user across devices."""

    __tablename__ = "user_settings"
    __table_args__ = (
        vocab_check("english_level", "englishLevel"),
        vocab_check("math_level", "mathLevel"),
        vocab_check("exploration", "explorationLevel"),
        vocab_check("translation_style", "translationStyle"),
        vocab_check("initial_translation_stage", "translationStage"),
        vocab_check("metric_signature", "metricSignature"),
        vocab_check("unit_system", "unitSystem"),
        vocab_check("canvas_style", "canvasStyle"),
        CheckConstraint("color_scheme IN ('system', 'light', 'dark')", name="ck_color_scheme"),
        CheckConstraint("offline_prefetch_count BETWEEN 0 AND 200", name="ck_offline_prefetch"),
        CheckConstraint("reshow_after_days BETWEEN 0 AND 3650", name="ck_reshow_after_days"),
    )

    user_id: Mapped[uuid.UUID] = mapped_column(
        UuidType, ForeignKey("users.id", ondelete="CASCADE"), primary_key=True
    )
    locale: Mapped[str] = mapped_column(String(16), nullable=False, default="ja-JP")
    timezone: Mapped[str] = mapped_column(String(64), nullable=False, default="Asia/Tokyo")
    color_scheme: Mapped[str] = mapped_column(String(16), nullable=False, default="system")
    english_level: Mapped[str] = mapped_column(String(32), nullable=False, default="intermediate")
    math_level: Mapped[str] = mapped_column(String(16), nullable=False, default="level_2")
    exploration: Mapped[str] = mapped_column(String(16), nullable=False, default="balanced")
    translation_style: Mapped[str] = mapped_column(String(32), nullable=False, default="natural")
    initial_translation_stage: Mapped[str] = mapped_column(
        String(32), nullable=False, default="natural"
    )
    metric_signature: Mapped[str] = mapped_column(
        String(32), nullable=False, default="as_published"
    )
    unit_system: Mapped[str] = mapped_column(String(32), nullable=False, default="si")
    canvas_style: Mapped[str] = mapped_column(String(32), nullable=False, default="mosaic")
    reduce_motion: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    haptics_enabled: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)
    high_contrast: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    offline_prefetch_count: Mapped[int] = mapped_column(Integer, nullable=False, default=20)
    reshow_after_days: Mapped[int] = mapped_column(Integer, nullable=False, default=90)
    #: Spec section 25: opt-in only, and off unless the user says otherwise.
    allow_selections_for_model_improvement: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=False
    )

    user: Mapped[User] = relationship(back_populates="settings")


class Field(Base, TimestampMixin):
    """Research field taxonomy (spec section 18)."""

    __tablename__ = "fields"

    id: Mapped[str] = mapped_column(String(64), primary_key=True)
    parent_id: Mapped[str | None] = mapped_column(
        String(64), ForeignKey("fields.id", ondelete="SET NULL"), nullable=True
    )
    label_en: Mapped[str] = mapped_column(String(160), nullable=False)
    label_ja: Mapped[str] = mapped_column(String(160), nullable=False)
    #: Base colour for canvas tiles (spec section 13).
    color: Mapped[str] = mapped_column(String(9), nullable=False, default="#667085")


class Interest(Base, TimestampMixin):
    __tablename__ = "interests"
    __table_args__ = (
        UniqueConstraint("user_id", "field_id", name="uq_interest_user_field"),
        vocab_check("mode", "interestMode"),
        CheckConstraint("strength BETWEEN 0 AND 1", name="ck_interest_strength"),
    )

    id: Mapped[uuid.UUID] = mapped_column(UuidType, primary_key=True, default=_uuid)
    user_id: Mapped[uuid.UUID] = mapped_column(
        UuidType, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True
    )
    field_id: Mapped[str] = mapped_column(
        String(64), ForeignKey("fields.id", ondelete="CASCADE"), nullable=False
    )
    strength: Mapped[float] = mapped_column(Float, nullable=False, default=1.0)
    mode: Mapped[str] = mapped_column(String(32), nullable=False, default="main")

    user: Mapped[User] = relationship(back_populates="interests")


# -------------------------------------------------------------------------- papers


class Paper(Base, TimestampMixin):
    """A work, after deduplication. One row per canonical paper (spec section 16)."""

    __tablename__ = "papers"
    __table_args__ = (
        vocab_check("open_access", "openAccessStatus"),
        vocab_check("retraction_status", "retractionStatus"),
        vocab_check("english_level", "englishLevel"),
        vocab_check("source_provider", "sourceProvider"),
        CheckConstraint("year BETWEEN 1600 AND 2200", name="ck_paper_year"),
        Index("ix_papers_primary_field_year", "primary_field_id", "year"),
        # The refresh worker's queue: "papers from this source, longest unchecked first".
        Index("ix_papers_refresh_queue", "source_provider", "last_refreshed_at"),
    )

    id: Mapped[uuid.UUID] = mapped_column(UuidType, primary_key=True, default=_uuid)
    canonical_id: Mapped[str] = mapped_column(String(400), nullable=False, unique=True, index=True)
    title: Mapped[str] = mapped_column(Text, nullable=False)
    #: Normalised form used for last-resort duplicate detection (spec section 16).
    normalized_title: Mapped[str] = mapped_column(Text, nullable=False, index=True)
    #: Original English abstract. A translation never overwrites this column.
    abstract: Mapped[str] = mapped_column(Text, nullable=False)
    authors: Mapped[list[dict[str, Any]]] = mapped_column(JsonType, nullable=False, default=list)
    year: Mapped[int] = mapped_column(Integer, nullable=False)
    venue: Mapped[str | None] = mapped_column(String(400), nullable=True)
    paper_types: Mapped[list[str]] = mapped_column(JsonType, nullable=False, default=list)
    primary_field_id: Mapped[str | None] = mapped_column(
        String(64), ForeignKey("fields.id", ondelete="SET NULL"), nullable=True
    )
    open_access: Mapped[str] = mapped_column(String(16), nullable=False, default="unknown")
    retraction_status: Mapped[str] = mapped_column(String(32), nullable=False, default="none")
    version: Mapped[str | None] = mapped_column(String(32), nullable=True)
    supersedes_paper_id: Mapped[uuid.UUID | None] = mapped_column(
        UuidType, ForeignKey("papers.id", ondelete="SET NULL"), nullable=True
    )
    english_level: Mapped[str] = mapped_column(String(32), nullable=False, default="intermediate")
    math_density: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    equation_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    estimated_reading_minutes: Mapped[float] = mapped_column(Float, nullable=False, default=1.0)

    # Provenance (spec section 21) — every column here is required reading before display.
    source_provider: Mapped[str] = mapped_column(String(32), nullable=False)
    source_url: Mapped[str] = mapped_column(Text, nullable=False)
    pdf_url: Mapped[str | None] = mapped_column(Text, nullable=True)
    acquired_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    #: When the refresh worker last asked the source about this paper. Deliberately *not*
    #: `acquired_at`: section 21 defines that one as provenance — when this copy was taken,
    #: as the provider reports it — while this is our own operational note about when we
    #: last checked. Ordering the refresh queue by `acquired_at` looked equivalent and was
    #: not: a provider that echoes back a fixed timestamp leaves every paper permanently
    #: stale, so the queue re-checks the same batch forever and never reaches the rest.
    last_refreshed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    license_id: Mapped[str | None] = mapped_column(String(64), nullable=True)
    license_url: Mapped[str | None] = mapped_column(Text, nullable=True)
    #: False when the terms do not permit storing or re-showing the abstract text.
    abstract_redistributable: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    cache_policy: Mapped[str] = mapped_column(String(32), nullable=False, default="metadata_only")
    #: Everything the provider returned, kept so a re-parse never needs a re-fetch.
    raw_metadata: Mapped[dict[str, Any]] = mapped_column(JsonType, nullable=False, default=dict)

    identifiers: Mapped[list[PaperIdentifier]] = relationship(
        back_populates="paper", cascade="all, delete-orphan"
    )
    field_weights: Mapped[list[PaperField]] = relationship(
        back_populates="paper", cascade="all, delete-orphan"
    )


class PaperIdentifier(Base):
    """Every identifier a paper is known by, including superseded ones after a merge."""

    __tablename__ = "paper_identifiers"
    __table_args__ = (
        UniqueConstraint("kind", "value", name="uq_identifier_kind_value"),
        vocab_check("kind", "identifierKind"),
        Index("ix_paper_identifiers_paper", "paper_id"),
    )

    id: Mapped[uuid.UUID] = mapped_column(UuidType, primary_key=True, default=_uuid)
    paper_id: Mapped[uuid.UUID] = mapped_column(
        UuidType, ForeignKey("papers.id", ondelete="CASCADE"), nullable=False
    )
    kind: Mapped[str] = mapped_column(String(32), nullable=False)
    #: Stored already normalised (lower-cased DOI, version-stripped arXiv id).
    value: Mapped[str] = mapped_column(String(400), nullable=False)

    paper: Mapped[Paper] = relationship(back_populates="identifiers")


class PaperField(Base):
    """Weighted field membership; drives canvas colour mixing (spec section 13)."""

    __tablename__ = "paper_fields"
    __table_args__ = (CheckConstraint("weight BETWEEN 0 AND 1", name="ck_paper_field_weight"),)

    paper_id: Mapped[uuid.UUID] = mapped_column(
        UuidType, ForeignKey("papers.id", ondelete="CASCADE"), primary_key=True
    )
    field_id: Mapped[str] = mapped_column(
        String(64), ForeignKey("fields.id", ondelete="CASCADE"), primary_key=True
    )
    weight: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)

    paper: Mapped[Paper] = relationship(back_populates="field_weights")


class AbstractSegment(Base):
    """Structural roles within an abstract (spec section 8).

    Stored as offsets so the original text is never modified by a classifier.
    """

    __tablename__ = "abstract_segments"
    __table_args__ = (
        vocab_check("section", "abstractSection"),
        vocab_check("detected_by", "detectionMethod"),
        CheckConstraint("start_offset >= 0 AND end_offset > start_offset", name="ck_segment_range"),
        Index("ix_abstract_segments_paper", "paper_id"),
    )

    id: Mapped[uuid.UUID] = mapped_column(UuidType, primary_key=True, default=_uuid)
    paper_id: Mapped[uuid.UUID] = mapped_column(
        UuidType, ForeignKey("papers.id", ondelete="CASCADE"), nullable=False
    )
    start_offset: Mapped[int] = mapped_column(Integer, nullable=False)
    end_offset: Mapped[int] = mapped_column(Integer, nullable=False)
    section: Mapped[str] = mapped_column(String(32), nullable=False)
    detected_by: Mapped[str] = mapped_column(String(16), nullable=False, default="heuristic")
    confidence: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)


class PaperRelation(Base, TimestampMixin):
    """Spec section 17: a relation always keeps the evidence that produced it."""

    __tablename__ = "paper_relations"
    __table_args__ = (
        UniqueConstraint(
            "source_paper_id", "target_paper_id", "relation_type", name="uq_paper_relation"
        ),
        vocab_check("relation_type", "relationType"),
        CheckConstraint("confidence BETWEEN 0 AND 1", name="ck_relation_confidence"),
    )

    id: Mapped[uuid.UUID] = mapped_column(UuidType, primary_key=True, default=_uuid)
    source_paper_id: Mapped[uuid.UUID] = mapped_column(
        UuidType, ForeignKey("papers.id", ondelete="CASCADE"), nullable=False, index=True
    )
    target_paper_id: Mapped[uuid.UUID] = mapped_column(
        UuidType, ForeignKey("papers.id", ondelete="CASCADE"), nullable=False, index=True
    )
    relation_type: Mapped[str] = mapped_column(String(32), nullable=False)
    confidence: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    #: Citation direction, publication order, mention snippet, model — never similarity alone.
    evidence: Mapped[dict[str, Any]] = mapped_column(JsonType, nullable=False, default=dict)


# ------------------------------------------------------------------ user activity


class Impression(Base):
    """Every card shown, so it is never shown again by accident (spec section 16)."""

    __tablename__ = "impressions"
    __table_args__ = (
        Index("ix_impressions_user_paper", "user_id", "paper_id"),
        Index("ix_impressions_user_shown_at", "user_id", "shown_at"),
    )

    id: Mapped[uuid.UUID] = mapped_column(UuidType, primary_key=True, default=_uuid)
    user_id: Mapped[uuid.UUID] = mapped_column(
        UuidType, ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    paper_id: Mapped[uuid.UUID] = mapped_column(
        UuidType, ForeignKey("papers.id", ondelete="CASCADE"), nullable=False
    )
    shown_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    position: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    feed_context: Mapped[str] = mapped_column(String(64), nullable=False, default="discover")
    dwell_ms: Mapped[int | None] = mapped_column(Integer, nullable=True)


#: Backs ``Action.sequence``. Declared at module level so Alembic emits the CREATE
#: SEQUENCE alongside the table.
ACTION_SEQUENCE = Sequence("actions_sequence_seq")


class Action(Base):
    """User actions, including the undo that reverses one (spec section 6)."""

    __tablename__ = "actions"
    __table_args__ = (
        vocab_check("action_type", "actionType"),
        Index("ix_actions_user_created", "user_id", "created_at"),
        Index("ix_actions_user_sequence", "user_id", "sequence"),
    )

    id: Mapped[uuid.UUID] = mapped_column(UuidType, primary_key=True, default=_uuid)
    #: Insertion order, and the only sound way to ask "what was the last action?".
    #: ``created_at`` uses ``now()``, which is the *transaction* clock in PostgreSQL, so
    #: two actions written in one request share a timestamp and cannot be ordered — and
    #: Undo has to know exactly which one it is reversing (spec section 6).
    sequence: Mapped[int] = mapped_column(
        BigInteger,
        ACTION_SEQUENCE,
        server_default=ACTION_SEQUENCE.next_value(),
        nullable=False,
        unique=True,
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        UuidType, ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    paper_id: Mapped[uuid.UUID | None] = mapped_column(
        UuidType, ForeignKey("papers.id", ondelete="CASCADE"), nullable=True
    )
    action_type: Mapped[str] = mapped_column(String(32), nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    undoes_action_id: Mapped[uuid.UUID | None] = mapped_column(
        UuidType, ForeignKey("actions.id", ondelete="SET NULL"), nullable=True
    )
    #: True once this action has itself been undone, so undo is idempotent.
    undone: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    payload: Mapped[dict[str, Any]] = mapped_column(JsonType, nullable=False, default=dict)


class SavedPaper(Base, TimestampMixin):
    __tablename__ = "saved_papers"
    __table_args__ = (
        UniqueConstraint("user_id", "paper_id", name="uq_saved_user_paper"),
        vocab_check("status", "savedStatus"),
        Index("ix_saved_user_status", "user_id", "status"),
    )

    id: Mapped[uuid.UUID] = mapped_column(UuidType, primary_key=True, default=_uuid)
    user_id: Mapped[uuid.UUID] = mapped_column(
        UuidType, ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    paper_id: Mapped[uuid.UUID] = mapped_column(
        UuidType, ForeignKey("papers.id", ondelete="CASCADE"), nullable=False
    )
    #: Values from the ``saveReason`` vocabulary; validated in the service layer because
    #: a CHECK constraint cannot see inside a JSON array portably.
    reasons: Mapped[list[str]] = mapped_column(JsonType, nullable=False, default=list)
    status: Mapped[str] = mapped_column(String(32), nullable=False, default="unread")
    priority: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    notes: Mapped[str | None] = mapped_column(Text, nullable=True)
    saved_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    last_visited_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)


class TextSelection(Base):
    """A span the user selected in an abstract (spec section 23).

    The offsets are paired with a hash of the exact text so a re-ingested abstract that
    shifted by a character does not silently re-anchor the selection somewhere else.
    """

    __tablename__ = "text_selections"
    __table_args__ = (
        CheckConstraint(
            "start_offset >= 0 AND end_offset > start_offset", name="ck_selection_range"
        ),
        CheckConstraint("field IN ('abstract', 'title')", name="ck_selection_field"),
        Index("ix_selections_user_paper", "user_id", "paper_id"),
    )

    id: Mapped[uuid.UUID] = mapped_column(UuidType, primary_key=True, default=_uuid)
    user_id: Mapped[uuid.UUID] = mapped_column(
        UuidType, ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    paper_id: Mapped[uuid.UUID] = mapped_column(
        UuidType, ForeignKey("papers.id", ondelete="CASCADE"), nullable=False
    )
    field: Mapped[str] = mapped_column(String(16), nullable=False, default="abstract")
    start_offset: Mapped[int] = mapped_column(Integer, nullable=False)
    end_offset: Mapped[int] = mapped_column(Integer, nullable=False)
    exact_text: Mapped[str] = mapped_column(Text, nullable=False)
    exact_text_hash: Mapped[str] = mapped_column(String(64), nullable=False)
    context_before: Mapped[str] = mapped_column(Text, nullable=False, default="")
    context_after: Mapped[str] = mapped_column(Text, nullable=False, default="")
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )


class GenerationProvenanceMixin:
    """Stamped on every AI-generated row (spec section 23, closing line)."""

    generation_provider: Mapped[str] = mapped_column(String(64), nullable=False)
    generation_model: Mapped[str] = mapped_column(String(128), nullable=False)
    prompt_version: Mapped[str] = mapped_column(String(64), nullable=False)
    #: Hash of the exact input, so identical requests are cacheable and auditable.
    input_hash: Mapped[str] = mapped_column(String(64), nullable=False, index=True)


class Translation(Base, GenerationProvenanceMixin):
    __tablename__ = "translations"
    __table_args__ = (
        vocab_check("style", "translationStyle"),
        vocab_check("stage", "translationStage"),
        Index("ix_translations_selection", "selection_id"),
    )

    id: Mapped[uuid.UUID] = mapped_column(UuidType, primary_key=True, default=_uuid)
    selection_id: Mapped[uuid.UUID | None] = mapped_column(
        UuidType, ForeignKey("text_selections.id", ondelete="SET NULL"), nullable=True
    )
    #: The English source, stored verbatim next to its translation so the pair is auditable.
    original: Mapped[str] = mapped_column(Text, nullable=False)
    translated: Mapped[str] = mapped_column(Text, nullable=False)
    style: Mapped[str] = mapped_column(String(32), nullable=False)
    stage: Mapped[str] = mapped_column(String(32), nullable=False)
    #: The token → LaTeX map used to protect formulas (spec section 7).
    math_placeholders: Mapped[list[dict[str, Any]]] = mapped_column(
        JsonType, nullable=False, default=list
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )


class ExpressionCard(Base, TimestampMixin):
    """Personal academic-English dictionary entry (spec section 9).

    The review columns live here rather than in a separate schedule table: an entry has
    exactly one schedule, and spec section 9 asks for a gentle "one item a few days later"
    rather than a full spaced-repetition system with its own history.
    """

    __tablename__ = "expression_cards"
    __table_args__ = (
        UniqueConstraint("user_id", "phrase", name="uq_expression_user_phrase"),
        vocab_check("kind", "expressionKind"),
        Index("ix_expressions_user", "user_id"),
        Index("ix_expressions_due", "user_id", "next_review_at"),
    )

    id: Mapped[uuid.UUID] = mapped_column(UuidType, primary_key=True, default=_uuid)
    user_id: Mapped[uuid.UUID] = mapped_column(
        UuidType, ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    source_paper_id: Mapped[uuid.UUID | None] = mapped_column(
        UuidType, ForeignKey("papers.id", ondelete="SET NULL"), nullable=True
    )
    kind: Mapped[str] = mapped_column(String(32), nullable=False, default="word")
    phrase: Mapped[str] = mapped_column(Text, nullable=False)
    meaning: Mapped[str] = mapped_column(Text, nullable=False)
    examples: Mapped[list[str]] = mapped_column(JsonType, nullable=False, default=list)
    #: The sentence the phrase came from. Spec section 9 asks for 実際に読んだ論文の用例 —
    #: an entry without its context is a flashcard, not a reading memory.
    context: Mapped[str | None] = mapped_column(Text, nullable=True)
    review_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    last_reviewed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    next_review_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)


# ---------------------------------------------------------------------- mathematics


class Equation(Base, TimestampMixin):
    """Spec section 11: LaTeX is the record of truth. No image column exists by design."""

    __tablename__ = "equations"
    __table_args__ = (
        vocab_check("provenance_kind", "provenanceKind"),
        vocab_check("verification_status", "verificationStatus"),
        Index("ix_equations_paper", "paper_id"),
    )

    id: Mapped[uuid.UUID] = mapped_column(UuidType, primary_key=True, default=_uuid)
    paper_id: Mapped[uuid.UUID] = mapped_column(
        UuidType, ForeignKey("papers.id", ondelete="CASCADE"), nullable=False
    )
    latex: Mapped[str] = mapped_column(Text, nullable=False)
    equation_number: Mapped[str | None] = mapped_column(String(32), nullable=True)
    section: Mapped[str | None] = mapped_column(String(120), nullable=True)
    display: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)
    provenance_kind: Mapped[str] = mapped_column(String(32), nullable=False, default="original")
    verification_status: Mapped[str] = mapped_column(
        String(32), nullable=False, default="source_exact"
    )
    license_id: Mapped[str | None] = mapped_column(String(64), nullable=True)
    generation: Mapped[dict[str, Any] | None] = mapped_column(JsonType, nullable=True)


class EquationSymbol(Base):
    __tablename__ = "equation_symbols"
    __table_args__ = (
        vocab_check("provenance_kind", "provenanceKind"),
        CheckConstraint(
            "scope IN ('equation', 'section', 'paper', 'field')", name="ck_symbol_scope"
        ),
        Index("ix_equation_symbols_equation", "equation_id"),
    )

    id: Mapped[uuid.UUID] = mapped_column(UuidType, primary_key=True, default=_uuid)
    equation_id: Mapped[uuid.UUID] = mapped_column(
        UuidType, ForeignKey("equations.id", ondelete="CASCADE"), nullable=False
    )
    symbol: Mapped[str] = mapped_column(String(120), nullable=False)
    local_meaning: Mapped[str] = mapped_column(Text, nullable=False)
    general_meaning: Mapped[str | None] = mapped_column(Text, nullable=True)
    defined_in_equation_id: Mapped[uuid.UUID | None] = mapped_column(
        UuidType, ForeignKey("equations.id", ondelete="SET NULL"), nullable=True
    )
    unit: Mapped[str | None] = mapped_column(String(64), nullable=True)
    scope: Mapped[str] = mapped_column(String(16), nullable=False, default="equation")
    provenance_kind: Mapped[str] = mapped_column(String(32), nullable=False, default="original")


class DerivationStep(Base, TimestampMixin):
    """One transformation between equations (spec section 12).

    ``verification_status`` decides visibility: anything outside the default-visible set
    is withheld unless the user explicitly asks for unverified content.
    """

    __tablename__ = "derivation_steps"
    __table_args__ = (
        vocab_check("provenance_kind", "provenanceKind"),
        vocab_check("verification_status", "verificationStatus"),
        Index("ix_derivation_steps_from", "from_equation_id"),
    )

    id: Mapped[uuid.UUID] = mapped_column(UuidType, primary_key=True, default=_uuid)
    from_equation_id: Mapped[uuid.UUID] = mapped_column(
        UuidType, ForeignKey("equations.id", ondelete="CASCADE"), nullable=False
    )
    to_equation_id: Mapped[uuid.UUID] = mapped_column(
        UuidType, ForeignKey("equations.id", ondelete="CASCADE"), nullable=False
    )
    latex: Mapped[str] = mapped_column(Text, nullable=False)
    operation: Mapped[str] = mapped_column(String(120), nullable=False)
    rationale: Mapped[str] = mapped_column(Text, nullable=False, default="")
    verification_status: Mapped[str] = mapped_column(
        String(32), nullable=False, default="unverified"
    )
    provenance_kind: Mapped[str] = mapped_column(
        String(32), nullable=False, default="ai_explanation"
    )
    generation: Mapped[dict[str, Any] | None] = mapped_column(JsonType, nullable=True)


class MathCard(Base, TimestampMixin):
    __tablename__ = "math_cards"
    __table_args__ = (
        vocab_check("card_type", "mathCardType"),
        vocab_check("level", "mathLevel"),
        vocab_check("provenance_kind", "provenanceKind"),
        CheckConstraint(
            "review_status IN ('draft', 'in_review', 'approved', 'rejected')",
            name="ck_math_card_review_status",
        ),
    )

    id: Mapped[uuid.UUID] = mapped_column(UuidType, primary_key=True, default=_uuid)
    card_type: Mapped[str] = mapped_column(String(32), nullable=False)
    title: Mapped[str] = mapped_column(Text, nullable=False)
    level: Mapped[str] = mapped_column(String(16), nullable=False, default="level_2")
    source_equation_ids: Mapped[list[str]] = mapped_column(JsonType, nullable=False, default=list)
    review_status: Mapped[str] = mapped_column(String(16), nullable=False, default="draft")
    provenance_kind: Mapped[str] = mapped_column(
        String(32), nullable=False, default="ai_explanation"
    )
    body: Mapped[dict[str, Any]] = mapped_column(JsonType, nullable=False, default=dict)


class ReviewEvent(Base):
    """Human review decisions (spec section 23)."""

    __tablename__ = "review_events"
    __table_args__ = (
        CheckConstraint(
            "entity_type IN ('math_card', 'derivation_step', 'equation')",
            name="ck_review_entity_type",
        ),
        CheckConstraint(
            "decision IN ('approved', 'rejected', 'needs_changes')", name="ck_review_decision"
        ),
        Index("ix_review_events_entity", "entity_type", "entity_id"),
    )

    id: Mapped[uuid.UUID] = mapped_column(UuidType, primary_key=True, default=_uuid)
    entity_type: Mapped[str] = mapped_column(String(32), nullable=False)
    entity_id: Mapped[uuid.UUID] = mapped_column(UuidType, nullable=False)
    reviewer_id: Mapped[uuid.UUID] = mapped_column(
        UuidType, ForeignKey("users.id", ondelete="SET NULL"), nullable=True
    )
    decision: Mapped[str] = mapped_column(String(32), nullable=False)
    notes: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )


# --------------------------------------------------------------- canvas & embeddings


class Embedding(Base):
    """Semantic vectors (spec sections 13, 16).

    Phase 0 stores the vector as JSON. Phase 3 adds a ``pgvector`` column and an ANN index
    alongside it — see DECISIONS.md — which is why ``model`` and ``version`` are part of
    the key from the start: a re-embedding must not silently mix vector spaces.
    """

    __tablename__ = "embeddings"
    __table_args__ = (
        UniqueConstraint(
            "entity_type", "entity_id", "model", "version", name="uq_embedding_entity_model"
        ),
        CheckConstraint(
            "entity_type IN ('paper', 'equation', 'expression')", name="ck_embedding_entity_type"
        ),
        CheckConstraint("dimensions > 0", name="ck_embedding_dimensions"),
    )

    id: Mapped[uuid.UUID] = mapped_column(UuidType, primary_key=True, default=_uuid)
    entity_type: Mapped[str] = mapped_column(String(32), nullable=False)
    entity_id: Mapped[uuid.UUID] = mapped_column(UuidType, nullable=False, index=True)
    model: Mapped[str] = mapped_column(String(128), nullable=False)
    version: Mapped[str] = mapped_column(String(32), nullable=False, default="v1")
    dimensions: Mapped[int] = mapped_column(Integer, nullable=False)
    vector_json: Mapped[list[float]] = mapped_column(JsonType, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )


class CanvasPosition(Base, TimestampMixin):
    """Stable 2-D placement (spec section 13: 座標は安定させる)."""

    __tablename__ = "canvas_positions"
    __table_args__ = (
        UniqueConstraint(
            "user_id", "entity_type", "entity_id", "layout_version", name="uq_canvas_entity_layout"
        ),
        CheckConstraint(
            "entity_type IN ('paper', 'equation', 'expression')", name="ck_canvas_entity_type"
        ),
    )

    id: Mapped[uuid.UUID] = mapped_column(UuidType, primary_key=True, default=_uuid)
    user_id: Mapped[uuid.UUID] = mapped_column(
        UuidType, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True
    )
    entity_type: Mapped[str] = mapped_column(String(32), nullable=False)
    entity_id: Mapped[uuid.UUID] = mapped_column(UuidType, nullable=False)
    x: Mapped[float] = mapped_column(Float, nullable=False)
    y: Mapped[float] = mapped_column(Float, nullable=False)
    cluster_id: Mapped[str | None] = mapped_column(String(64), nullable=True)
    #: Which layout algorithm produced this position; kept so a re-layout is reversible.
    layout_version: Mapped[str] = mapped_column(String(32), nullable=False, default="mosaic-v1")
    #: True when the user dragged the tile; re-layouts must not move it (spec section 15).
    user_override: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)


class Collection(Base, TimestampMixin):
    __tablename__ = "collections"

    id: Mapped[uuid.UUID] = mapped_column(UuidType, primary_key=True, default=_uuid)
    user_id: Mapped[uuid.UUID] = mapped_column(
        UuidType, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True
    )
    name: Mapped[str] = mapped_column(String(160), nullable=False)
    style: Mapped[str | None] = mapped_column(String(64), nullable=True)


class CollectionItem(Base):
    __tablename__ = "collection_items"
    __table_args__ = (
        CheckConstraint(
            "entity_type IN ('paper', 'equation', 'expression')", name="ck_collection_entity_type"
        ),
    )

    collection_id: Mapped[uuid.UUID] = mapped_column(
        UuidType, ForeignKey("collections.id", ondelete="CASCADE"), primary_key=True
    )
    entity_type: Mapped[str] = mapped_column(String(32), primary_key=True)
    entity_id: Mapped[uuid.UUID] = mapped_column(UuidType, primary_key=True)
    position: Mapped[int] = mapped_column(Integer, nullable=False, default=0)


class AuditLog(Base):
    """Append-only record of consequential events (spec section 0: 監査ログ).

    Used for ingestion runs, provider failures, licence decisions, retraction syncs and
    data deletion — anything where "why does the app show this?" needs an answer later.
    """

    __tablename__ = "audit_log"
    __table_args__ = (Index("ix_audit_log_kind_created", "kind", "created_at"),)

    id: Mapped[uuid.UUID] = mapped_column(UuidType, primary_key=True, default=_uuid)
    kind: Mapped[str] = mapped_column(String(64), nullable=False)
    actor: Mapped[str] = mapped_column(String(64), nullable=False, default="system")
    entity_type: Mapped[str | None] = mapped_column(String(32), nullable=True)
    entity_id: Mapped[str | None] = mapped_column(String(400), nullable=True)
    detail: Mapped[dict[str, Any]] = mapped_column(JsonType, nullable=False, default=dict)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )


class IngestionRun(Base):
    """One execution of one ingestion job (spec sections 21, 27).

    This table exists for two reasons the spec states directly.

    Section 21 requires 削除・訂正・撤回情報を反映できる — a source of truth that changes
    after we copied it. Meeting that means going back to papers we already hold and asking
    again, which is a second kind of run with its own schedule.

    Section 27 lists 同一ソースへの過剰APIアクセス as a guardrail. Without somewhere to
    record how far a run got, every cycle would restart from the first page of every
    source. `cursor` is what makes the next run resume instead of re-fetch.

    A run row is both the record of what happened and the state the next run reads. That
    dual purpose is deliberate: an operator asking "why has nothing new appeared since
    Tuesday" and the scheduler asking "where do I start" want the same row.
    """

    __tablename__ = "ingestion_runs"
    __table_args__ = (
        CheckConstraint(
            "status IN ('running', 'succeeded', 'failed')", name="ck_ingestion_run_status"
        ),
        CheckConstraint("kind IN ('discovery', 'refresh')", name="ck_ingestion_run_kind"),
        Index("ix_ingestion_runs_job", "source", "job", "started_at"),
    )

    id: Mapped[uuid.UUID] = mapped_column(UuidType, primary_key=True, default=_uuid)
    #: Provider name, so two sources never resume from each other's cursor.
    source: Mapped[str] = mapped_column(String(32), nullable=False)
    #: Which slice of that source. `field:hep-th` and `field:cs.LG` page independently.
    job: Mapped[str] = mapped_column(String(128), nullable=False)
    kind: Mapped[str] = mapped_column(String(16), nullable=False, default="discovery")
    status: Mapped[str] = mapped_column(String(16), nullable=False, default="running")
    started_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    finished_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    #: Where this run stopped. Only read from runs that succeeded — a cursor from a failed
    #: run points into a page that may never have been stored.
    cursor: Mapped[str | None] = mapped_column(Text, nullable=True)
    counts: Mapped[dict[str, Any]] = mapped_column(JsonType, nullable=False, default=dict)
    #: Why it failed, in the operator's words rather than a stack trace.
    error: Mapped[str | None] = mapped_column(Text, nullable=True)


class ContentReport(Base):
    """A reader saying something looks wrong (spec sections 12, 27).

    Deliberately **not** a `review_events` row. That table records a *decision* —
    approved, rejected, needs_changes — made by someone with the standing to make it. This
    records a *report*: a reader who has spotted something and has no authority over what
    happens next, and should not be given the vocabulary of one. Storing both in one table
    would make "approved" a thing an anonymous guest can assert.

    It also does not touch `verification_status`. That column is the record of which
    mechanical checks ran and what they returned; a reader's opinion is not a check, and
    letting a report change it would put a claim nobody verified into a field whose entire
    value is that everything in it was.

    Section 27 counts these — AI説明の問題報告率 is a guardrail — which is why the report
    names the entity rather than just the card: `equations` and `derivation_steps` carry
    `provenance_kind`, so reports can be split by whether the thing reported came from the
    paper or from a model.
    """

    __tablename__ = "content_reports"
    __table_args__ = (
        CheckConstraint(
            "entity_type IN ('math_card', 'derivation_step', 'equation')",
            name="ck_content_report_entity_type",
        ),
        vocab_check("reason", "reportReason"),
        vocab_check("status", "reportStatus"),
        # One report per reader per problem per thing. A reader tapping twice is not two
        # readers, and section 27's metric is a *rate* — duplicates would inflate it.
        UniqueConstraint(
            "user_id", "entity_type", "entity_id", "reason", name="uq_content_report_once"
        ),
        Index("ix_content_reports_entity", "entity_type", "entity_id"),
        Index("ix_content_reports_status", "status", "created_at"),
    )

    id: Mapped[uuid.UUID] = mapped_column(UuidType, primary_key=True, default=_uuid)
    user_id: Mapped[uuid.UUID | None] = mapped_column(
        UuidType, ForeignKey("users.id", ondelete="SET NULL"), nullable=True
    )
    entity_type: Mapped[str] = mapped_column(String(32), nullable=False)
    entity_id: Mapped[uuid.UUID] = mapped_column(UuidType, nullable=False)
    #: The card the reader was looking at, even when they reported one step of it. Without
    #: it a step report cannot be shown next to the card it belongs to.
    math_card_id: Mapped[uuid.UUID | None] = mapped_column(
        UuidType, ForeignKey("math_cards.id", ondelete="CASCADE"), nullable=True
    )
    reason: Mapped[str] = mapped_column(String(48), nullable=False)
    #: The reader's own words. Optional, and bounded — this is a report, not a discussion.
    detail: Mapped[str | None] = mapped_column(Text, nullable=True)
    status: Mapped[str] = mapped_column(String(16), nullable=False, default="new")
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False
    )
