"""initial schema

The Phase 0 schema for every entity in spec section 23.

Two things to know when extending it:

* Vocabulary columns are ``VARCHAR`` with ``CHECK`` constraints generated from
  ``packages/shared-types/enums.json``. Adding a value means regenerating the constraint
  in a new migration — a one-line ``op.drop_constraint`` / ``op.create_check_constraint``
  pair — not an ``ALTER TYPE``.
* ``embeddings.vector_json`` holds vectors as JSON. The pgvector column and its ANN index
  arrive in Phase 3 (see DECISIONS.md, D-006), when there is something to search; Phase 0
  has no vector query and no reason to require the extension.

Revision ID: 0001_initial
Revises:
Create Date: 2026-07-30
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column("id", sa.UUID().with_variant(sa.String(length=36), "sqlite"), nullable=False),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("actor", sa.String(length=64), nullable=False),
        sa.Column("entity_type", sa.String(length=32), nullable=True),
        sa.Column("entity_id", sa.String(length=400), nullable=True),
        sa.Column(
            "detail",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_audit_log_kind_created", "audit_log", ["kind", "created_at"], unique=False)
    op.create_table(
        "embeddings",
        sa.Column("id", sa.UUID().with_variant(sa.String(length=36), "sqlite"), nullable=False),
        sa.Column("entity_type", sa.String(length=32), nullable=False),
        sa.Column(
            "entity_id", sa.UUID().with_variant(sa.String(length=36), "sqlite"), nullable=False
        ),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("version", sa.String(length=32), nullable=False),
        sa.Column("dimensions", sa.Integer(), nullable=False),
        sa.Column(
            "vector_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "entity_type IN ('paper', 'equation', 'expression')", name="ck_embedding_entity_type"
        ),
        sa.CheckConstraint("dimensions > 0", name="ck_embedding_dimensions"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "entity_type", "entity_id", "model", "version", name="uq_embedding_entity_model"
        ),
    )
    op.create_index(op.f("ix_embeddings_entity_id"), "embeddings", ["entity_id"], unique=False)
    op.create_table(
        "fields",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("parent_id", sa.String(length=64), nullable=True),
        sa.Column("label_en", sa.String(length=160), nullable=False),
        sa.Column("label_ja", sa.String(length=160), nullable=False),
        sa.Column("color", sa.String(length=9), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["parent_id"], ["fields.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "math_cards",
        sa.Column("id", sa.UUID().with_variant(sa.String(length=36), "sqlite"), nullable=False),
        sa.Column("card_type", sa.String(length=32), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("level", sa.String(length=16), nullable=False),
        sa.Column(
            "source_equation_ids",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("review_status", sa.String(length=16), nullable=False),
        sa.Column("provenance_kind", sa.String(length=32), nullable=False),
        sa.Column(
            "body",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "card_type IN ('derivation', 'definition', 'physical_meaning', 'approximation', 'consistency_check', 'notation', 'connection')",
            name="ck_card_type_mathcardtype",
        ),
        sa.CheckConstraint(
            "level IN ('level_0', 'level_1', 'level_2', 'level_3', 'level_4')",
            name="ck_level_mathlevel",
        ),
        sa.CheckConstraint(
            "provenance_kind IN ('original', 'verified_step', 'ai_explanation', 'assumption', 'human_reviewed')",
            name="ck_provenance_kind_provenancekind",
        ),
        sa.CheckConstraint(
            "review_status IN ('draft', 'in_review', 'approved', 'rejected')",
            name="ck_math_card_review_status",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID().with_variant(sa.String(length=36), "sqlite"), nullable=False),
        sa.Column("is_guest", sa.Boolean(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("display_name", sa.String(length=120), nullable=True),
        sa.Column("onboarding_completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "canvas_positions",
        sa.Column("id", sa.UUID().with_variant(sa.String(length=36), "sqlite"), nullable=False),
        sa.Column(
            "user_id", sa.UUID().with_variant(sa.String(length=36), "sqlite"), nullable=False
        ),
        sa.Column("entity_type", sa.String(length=32), nullable=False),
        sa.Column(
            "entity_id", sa.UUID().with_variant(sa.String(length=36), "sqlite"), nullable=False
        ),
        sa.Column("x", sa.Float(), nullable=False),
        sa.Column("y", sa.Float(), nullable=False),
        sa.Column("cluster_id", sa.String(length=64), nullable=True),
        sa.Column("layout_version", sa.String(length=32), nullable=False),
        sa.Column("user_override", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "entity_type IN ('paper', 'equation', 'expression')", name="ck_canvas_entity_type"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "entity_type", "entity_id", "layout_version", name="uq_canvas_entity_layout"
        ),
    )
    op.create_index(
        op.f("ix_canvas_positions_user_id"), "canvas_positions", ["user_id"], unique=False
    )
    op.create_table(
        "collections",
        sa.Column("id", sa.UUID().with_variant(sa.String(length=36), "sqlite"), nullable=False),
        sa.Column(
            "user_id", sa.UUID().with_variant(sa.String(length=36), "sqlite"), nullable=False
        ),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("style", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_collections_user_id"), "collections", ["user_id"], unique=False)
    op.create_table(
        "interests",
        sa.Column("id", sa.UUID().with_variant(sa.String(length=36), "sqlite"), nullable=False),
        sa.Column(
            "user_id", sa.UUID().with_variant(sa.String(length=36), "sqlite"), nullable=False
        ),
        sa.Column("field_id", sa.String(length=64), nullable=False),
        sa.Column("strength", sa.Float(), nullable=False),
        sa.Column("mode", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "mode IN ('main', 'occasional', 'serendipity')", name="ck_mode_interestmode"
        ),
        sa.CheckConstraint("strength BETWEEN 0 AND 1", name="ck_interest_strength"),
        sa.ForeignKeyConstraint(["field_id"], ["fields.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "field_id", name="uq_interest_user_field"),
    )
    op.create_index(op.f("ix_interests_user_id"), "interests", ["user_id"], unique=False)
    op.create_table(
        "papers",
        sa.Column("id", sa.UUID().with_variant(sa.String(length=36), "sqlite"), nullable=False),
        sa.Column("canonical_id", sa.String(length=400), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("normalized_title", sa.Text(), nullable=False),
        sa.Column("abstract", sa.Text(), nullable=False),
        sa.Column(
            "authors",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("venue", sa.String(length=400), nullable=True),
        sa.Column(
            "paper_types",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("primary_field_id", sa.String(length=64), nullable=True),
        sa.Column("open_access", sa.String(length=16), nullable=False),
        sa.Column("retraction_status", sa.String(length=32), nullable=False),
        sa.Column("version", sa.String(length=32), nullable=True),
        sa.Column(
            "supersedes_paper_id",
            sa.UUID().with_variant(sa.String(length=36), "sqlite"),
            nullable=True,
        ),
        sa.Column("english_level", sa.String(length=32), nullable=False),
        sa.Column("math_density", sa.Float(), nullable=False),
        sa.Column("equation_count", sa.Integer(), nullable=False),
        sa.Column("estimated_reading_minutes", sa.Float(), nullable=False),
        sa.Column("source_provider", sa.String(length=32), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("pdf_url", sa.Text(), nullable=True),
        sa.Column("acquired_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("license_id", sa.String(length=64), nullable=True),
        sa.Column("license_url", sa.Text(), nullable=True),
        sa.Column("abstract_redistributable", sa.Boolean(), nullable=False),
        sa.Column("cache_policy", sa.String(length=32), nullable=False),
        sa.Column(
            "raw_metadata",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "english_level IN ('beginner', 'intermediate', 'advanced', 'native_like')",
            name="ck_english_level_englishlevel",
        ),
        sa.CheckConstraint(
            "open_access IN ('gold', 'green', 'hybrid', 'bronze', 'closed', 'unknown')",
            name="ck_open_access_openaccessstatus",
        ),
        sa.CheckConstraint(
            "retraction_status IN ('none', 'corrected', 'concern_expressed', 'withdrawn', 'retracted')",
            name="ck_retraction_status_retractionstatus",
        ),
        sa.CheckConstraint(
            "source_provider IN ('arxiv', 'openalex', 'semantic_scholar', 'crossref', 'mock', 'manual')",
            name="ck_source_provider_sourceprovider",
        ),
        sa.CheckConstraint("year BETWEEN 1600 AND 2200", name="ck_paper_year"),
        sa.ForeignKeyConstraint(["primary_field_id"], ["fields.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["supersedes_paper_id"], ["papers.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_papers_canonical_id"), "papers", ["canonical_id"], unique=True)
    op.create_index(
        op.f("ix_papers_normalized_title"), "papers", ["normalized_title"], unique=False
    )
    op.create_index(
        "ix_papers_primary_field_year", "papers", ["primary_field_id", "year"], unique=False
    )
    op.create_table(
        "review_events",
        sa.Column("id", sa.UUID().with_variant(sa.String(length=36), "sqlite"), nullable=False),
        sa.Column("entity_type", sa.String(length=32), nullable=False),
        sa.Column(
            "entity_id", sa.UUID().with_variant(sa.String(length=36), "sqlite"), nullable=False
        ),
        sa.Column(
            "reviewer_id", sa.UUID().with_variant(sa.String(length=36), "sqlite"), nullable=True
        ),
        sa.Column("decision", sa.String(length=32), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "decision IN ('approved', 'rejected', 'needs_changes')", name="ck_review_decision"
        ),
        sa.CheckConstraint(
            "entity_type IN ('math_card', 'derivation_step', 'equation')",
            name="ck_review_entity_type",
        ),
        sa.ForeignKeyConstraint(["reviewer_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_review_events_entity", "review_events", ["entity_type", "entity_id"], unique=False
    )
    op.create_table(
        "user_settings",
        sa.Column(
            "user_id", sa.UUID().with_variant(sa.String(length=36), "sqlite"), nullable=False
        ),
        sa.Column("locale", sa.String(length=16), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("color_scheme", sa.String(length=16), nullable=False),
        sa.Column("english_level", sa.String(length=32), nullable=False),
        sa.Column("math_level", sa.String(length=16), nullable=False),
        sa.Column("exploration", sa.String(length=16), nullable=False),
        sa.Column("translation_style", sa.String(length=32), nullable=False),
        sa.Column("initial_translation_stage", sa.String(length=32), nullable=False),
        sa.Column("metric_signature", sa.String(length=32), nullable=False),
        sa.Column("unit_system", sa.String(length=32), nullable=False),
        sa.Column("canvas_style", sa.String(length=32), nullable=False),
        sa.Column("reduce_motion", sa.Boolean(), nullable=False),
        sa.Column("haptics_enabled", sa.Boolean(), nullable=False),
        sa.Column("high_contrast", sa.Boolean(), nullable=False),
        sa.Column("offline_prefetch_count", sa.Integer(), nullable=False),
        sa.Column("reshow_after_days", sa.Integer(), nullable=False),
        sa.Column("allow_selections_for_model_improvement", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "canvas_style IN ('mosaic', 'constellation', 'landscape', 'spectrum')",
            name="ck_canvas_style_canvasstyle",
        ),
        sa.CheckConstraint("color_scheme IN ('system', 'light', 'dark')", name="ck_color_scheme"),
        sa.CheckConstraint(
            "english_level IN ('beginner', 'intermediate', 'advanced', 'native_like')",
            name="ck_english_level_englishlevel",
        ),
        sa.CheckConstraint(
            "exploration IN ('focused', 'balanced', 'adventurous')",
            name="ck_exploration_explorationlevel",
        ),
        sa.CheckConstraint(
            "initial_translation_stage IN ('hard_words', 'sentence_skeleton', 'phrase_structure', 'literal', 'natural', 'domain_meaning')",
            name="ck_initial_translation_stage_translationstage",
        ),
        sa.CheckConstraint(
            "math_level IN ('level_0', 'level_1', 'level_2', 'level_3', 'level_4')",
            name="ck_math_level_mathlevel",
        ),
        sa.CheckConstraint(
            "metric_signature IN ('as_published', 'mostly_minus', 'mostly_plus')",
            name="ck_metric_signature_metricsignature",
        ),
        sa.CheckConstraint(
            "translation_style IN ('natural', 'faithful', 'literal', 'academic', 'plain_japanese')",
            name="ck_translation_style_translationstyle",
        ),
        sa.CheckConstraint(
            "unit_system IN ('si', 'gaussian', 'heaviside_lorentz', 'natural', 'geometric')",
            name="ck_unit_system_unitsystem",
        ),
        sa.CheckConstraint("offline_prefetch_count BETWEEN 0 AND 200", name="ck_offline_prefetch"),
        sa.CheckConstraint("reshow_after_days BETWEEN 0 AND 3650", name="ck_reshow_after_days"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "abstract_segments",
        sa.Column("id", sa.UUID().with_variant(sa.String(length=36), "sqlite"), nullable=False),
        sa.Column(
            "paper_id", sa.UUID().with_variant(sa.String(length=36), "sqlite"), nullable=False
        ),
        sa.Column("start_offset", sa.Integer(), nullable=False),
        sa.Column("end_offset", sa.Integer(), nullable=False),
        sa.Column("section", sa.String(length=32), nullable=False),
        sa.Column("detected_by", sa.String(length=16), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.CheckConstraint(
            "detected_by IN ('ai', 'source', 'human')", name="ck_segment_detected_by"
        ),
        sa.CheckConstraint(
            "section IN ('background', 'problem', 'method', 'result', 'significance')",
            name="ck_section_abstractsection",
        ),
        sa.CheckConstraint(
            "start_offset >= 0 AND end_offset > start_offset", name="ck_segment_range"
        ),
        sa.ForeignKeyConstraint(["paper_id"], ["papers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_abstract_segments_paper", "abstract_segments", ["paper_id"], unique=False)
    op.create_table(
        "actions",
        sa.Column("id", sa.UUID().with_variant(sa.String(length=36), "sqlite"), nullable=False),
        sa.Column(
            "user_id", sa.UUID().with_variant(sa.String(length=36), "sqlite"), nullable=False
        ),
        sa.Column(
            "paper_id", sa.UUID().with_variant(sa.String(length=36), "sqlite"), nullable=True
        ),
        sa.Column("action_type", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "undoes_action_id",
            sa.UUID().with_variant(sa.String(length=36), "sqlite"),
            nullable=True,
        ),
        sa.Column("undone", sa.Boolean(), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "action_type IN ('skip', 'save', 'open_source', 'translate', 'expand_math', 'hide_topic', 'hide_author', 'undo')",
            name="ck_action_type_actiontype",
        ),
        sa.ForeignKeyConstraint(["paper_id"], ["papers.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["undoes_action_id"], ["actions.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_actions_user_created", "actions", ["user_id", "created_at"], unique=False)
    op.create_table(
        "collection_items",
        sa.Column(
            "collection_id", sa.UUID().with_variant(sa.String(length=36), "sqlite"), nullable=False
        ),
        sa.Column("entity_type", sa.String(length=32), nullable=False),
        sa.Column(
            "entity_id", sa.UUID().with_variant(sa.String(length=36), "sqlite"), nullable=False
        ),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "entity_type IN ('paper', 'equation', 'expression')", name="ck_collection_entity_type"
        ),
        sa.ForeignKeyConstraint(["collection_id"], ["collections.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("collection_id", "entity_type", "entity_id"),
    )
    op.create_table(
        "equations",
        sa.Column("id", sa.UUID().with_variant(sa.String(length=36), "sqlite"), nullable=False),
        sa.Column(
            "paper_id", sa.UUID().with_variant(sa.String(length=36), "sqlite"), nullable=False
        ),
        sa.Column("latex", sa.Text(), nullable=False),
        sa.Column("equation_number", sa.String(length=32), nullable=True),
        sa.Column("section", sa.String(length=120), nullable=True),
        sa.Column("display", sa.Boolean(), nullable=False),
        sa.Column("provenance_kind", sa.String(length=32), nullable=False),
        sa.Column("verification_status", sa.String(length=32), nullable=False),
        sa.Column("license_id", sa.String(length=64), nullable=True),
        sa.Column(
            "generation",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "provenance_kind IN ('original', 'verified_step', 'ai_explanation', 'assumption', 'human_reviewed')",
            name="ck_provenance_kind_provenancekind",
        ),
        sa.CheckConstraint(
            "verification_status IN ('source_exact', 'mechanically_verified', 'dimensionally_checked', 'numerically_spot_checked', 'human_reviewed', 'unverified')",
            name="ck_verification_status_verificationstatus",
        ),
        sa.ForeignKeyConstraint(["paper_id"], ["papers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_equations_paper", "equations", ["paper_id"], unique=False)
    op.create_table(
        "expression_cards",
        sa.Column("id", sa.UUID().with_variant(sa.String(length=36), "sqlite"), nullable=False),
        sa.Column(
            "user_id", sa.UUID().with_variant(sa.String(length=36), "sqlite"), nullable=False
        ),
        sa.Column(
            "source_paper_id", sa.UUID().with_variant(sa.String(length=36), "sqlite"), nullable=True
        ),
        sa.Column("phrase", sa.Text(), nullable=False),
        sa.Column("meaning", sa.Text(), nullable=False),
        sa.Column(
            "examples",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["source_paper_id"], ["papers.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_expressions_user", "expression_cards", ["user_id"], unique=False)
    op.create_table(
        "impressions",
        sa.Column("id", sa.UUID().with_variant(sa.String(length=36), "sqlite"), nullable=False),
        sa.Column(
            "user_id", sa.UUID().with_variant(sa.String(length=36), "sqlite"), nullable=False
        ),
        sa.Column(
            "paper_id", sa.UUID().with_variant(sa.String(length=36), "sqlite"), nullable=False
        ),
        sa.Column(
            "shown_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("feed_context", sa.String(length=64), nullable=False),
        sa.Column("dwell_ms", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["paper_id"], ["papers.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_impressions_user_paper", "impressions", ["user_id", "paper_id"], unique=False
    )
    op.create_index(
        "ix_impressions_user_shown_at", "impressions", ["user_id", "shown_at"], unique=False
    )
    op.create_table(
        "paper_fields",
        sa.Column(
            "paper_id", sa.UUID().with_variant(sa.String(length=36), "sqlite"), nullable=False
        ),
        sa.Column("field_id", sa.String(length=64), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.CheckConstraint("weight BETWEEN 0 AND 1", name="ck_paper_field_weight"),
        sa.ForeignKeyConstraint(["field_id"], ["fields.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["paper_id"], ["papers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("paper_id", "field_id"),
    )
    op.create_table(
        "paper_identifiers",
        sa.Column("id", sa.UUID().with_variant(sa.String(length=36), "sqlite"), nullable=False),
        sa.Column(
            "paper_id", sa.UUID().with_variant(sa.String(length=36), "sqlite"), nullable=False
        ),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("value", sa.String(length=400), nullable=False),
        sa.CheckConstraint(
            "kind IN ('doi', 'arxiv', 'semantic_scholar', 'openalex', 'title_author_year')",
            name="ck_kind_identifierkind",
        ),
        sa.ForeignKeyConstraint(["paper_id"], ["papers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("kind", "value", name="uq_identifier_kind_value"),
    )
    op.create_index("ix_paper_identifiers_paper", "paper_identifiers", ["paper_id"], unique=False)
    op.create_table(
        "paper_relations",
        sa.Column("id", sa.UUID().with_variant(sa.String(length=36), "sqlite"), nullable=False),
        sa.Column(
            "source_paper_id",
            sa.UUID().with_variant(sa.String(length=36), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "target_paper_id",
            sa.UUID().with_variant(sa.String(length=36), "sqlite"),
            nullable=False,
        ),
        sa.Column("relation_type", sa.String(length=32), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column(
            "evidence",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "relation_type IN ('related', 'contrasting', 'foundational', 'follow_up')",
            name="ck_relation_type_relationtype",
        ),
        sa.CheckConstraint("confidence BETWEEN 0 AND 1", name="ck_relation_confidence"),
        sa.ForeignKeyConstraint(["source_paper_id"], ["papers.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["target_paper_id"], ["papers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "source_paper_id", "target_paper_id", "relation_type", name="uq_paper_relation"
        ),
    )
    op.create_index(
        op.f("ix_paper_relations_source_paper_id"),
        "paper_relations",
        ["source_paper_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_paper_relations_target_paper_id"),
        "paper_relations",
        ["target_paper_id"],
        unique=False,
    )
    op.create_table(
        "saved_papers",
        sa.Column("id", sa.UUID().with_variant(sa.String(length=36), "sqlite"), nullable=False),
        sa.Column(
            "user_id", sa.UUID().with_variant(sa.String(length=36), "sqlite"), nullable=False
        ),
        sa.Column(
            "paper_id", sa.UUID().with_variant(sa.String(length=36), "sqlite"), nullable=False
        ),
        sa.Column(
            "reasons",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "saved_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("last_visited_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('unread', 'abstract_in_progress', 'abstract_done', 'source_opened', 'focus', 'finished', 'archived')",
            name="ck_status_savedstatus",
        ),
        sa.ForeignKeyConstraint(["paper_id"], ["papers.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "paper_id", name="uq_saved_user_paper"),
    )
    op.create_index("ix_saved_user_status", "saved_papers", ["user_id", "status"], unique=False)
    op.create_table(
        "text_selections",
        sa.Column("id", sa.UUID().with_variant(sa.String(length=36), "sqlite"), nullable=False),
        sa.Column(
            "user_id", sa.UUID().with_variant(sa.String(length=36), "sqlite"), nullable=False
        ),
        sa.Column(
            "paper_id", sa.UUID().with_variant(sa.String(length=36), "sqlite"), nullable=False
        ),
        sa.Column("field", sa.String(length=16), nullable=False),
        sa.Column("start_offset", sa.Integer(), nullable=False),
        sa.Column("end_offset", sa.Integer(), nullable=False),
        sa.Column("exact_text", sa.Text(), nullable=False),
        sa.Column("exact_text_hash", sa.String(length=64), nullable=False),
        sa.Column("context_before", sa.Text(), nullable=False),
        sa.Column("context_after", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("field IN ('abstract', 'title')", name="ck_selection_field"),
        sa.CheckConstraint(
            "start_offset >= 0 AND end_offset > start_offset", name="ck_selection_range"
        ),
        sa.ForeignKeyConstraint(["paper_id"], ["papers.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_selections_user_paper", "text_selections", ["user_id", "paper_id"], unique=False
    )
    op.create_table(
        "derivation_steps",
        sa.Column("id", sa.UUID().with_variant(sa.String(length=36), "sqlite"), nullable=False),
        sa.Column(
            "from_equation_id",
            sa.UUID().with_variant(sa.String(length=36), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "to_equation_id", sa.UUID().with_variant(sa.String(length=36), "sqlite"), nullable=False
        ),
        sa.Column("latex", sa.Text(), nullable=False),
        sa.Column("operation", sa.String(length=120), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("verification_status", sa.String(length=32), nullable=False),
        sa.Column("provenance_kind", sa.String(length=32), nullable=False),
        sa.Column(
            "generation",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "provenance_kind IN ('original', 'verified_step', 'ai_explanation', 'assumption', 'human_reviewed')",
            name="ck_provenance_kind_provenancekind",
        ),
        sa.CheckConstraint(
            "verification_status IN ('source_exact', 'mechanically_verified', 'dimensionally_checked', 'numerically_spot_checked', 'human_reviewed', 'unverified')",
            name="ck_verification_status_verificationstatus",
        ),
        sa.ForeignKeyConstraint(["from_equation_id"], ["equations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["to_equation_id"], ["equations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_derivation_steps_from", "derivation_steps", ["from_equation_id"], unique=False
    )
    op.create_table(
        "equation_symbols",
        sa.Column("id", sa.UUID().with_variant(sa.String(length=36), "sqlite"), nullable=False),
        sa.Column(
            "equation_id", sa.UUID().with_variant(sa.String(length=36), "sqlite"), nullable=False
        ),
        sa.Column("symbol", sa.String(length=120), nullable=False),
        sa.Column("local_meaning", sa.Text(), nullable=False),
        sa.Column("general_meaning", sa.Text(), nullable=True),
        sa.Column(
            "defined_in_equation_id",
            sa.UUID().with_variant(sa.String(length=36), "sqlite"),
            nullable=True,
        ),
        sa.Column("unit", sa.String(length=64), nullable=True),
        sa.Column("scope", sa.String(length=16), nullable=False),
        sa.Column("provenance_kind", sa.String(length=32), nullable=False),
        sa.CheckConstraint(
            "provenance_kind IN ('original', 'verified_step', 'ai_explanation', 'assumption', 'human_reviewed')",
            name="ck_provenance_kind_provenancekind",
        ),
        sa.CheckConstraint(
            "scope IN ('equation', 'section', 'paper', 'field')", name="ck_symbol_scope"
        ),
        sa.ForeignKeyConstraint(["defined_in_equation_id"], ["equations.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["equation_id"], ["equations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_equation_symbols_equation", "equation_symbols", ["equation_id"], unique=False
    )
    op.create_table(
        "translations",
        sa.Column("id", sa.UUID().with_variant(sa.String(length=36), "sqlite"), nullable=False),
        sa.Column(
            "selection_id", sa.UUID().with_variant(sa.String(length=36), "sqlite"), nullable=True
        ),
        sa.Column("original", sa.Text(), nullable=False),
        sa.Column("translated", sa.Text(), nullable=False),
        sa.Column("style", sa.String(length=32), nullable=False),
        sa.Column("stage", sa.String(length=32), nullable=False),
        sa.Column(
            "math_placeholders",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("generation_provider", sa.String(length=64), nullable=False),
        sa.Column("generation_model", sa.String(length=128), nullable=False),
        sa.Column("prompt_version", sa.String(length=64), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "stage IN ('hard_words', 'sentence_skeleton', 'phrase_structure', 'literal', 'natural', 'domain_meaning')",
            name="ck_stage_translationstage",
        ),
        sa.CheckConstraint(
            "style IN ('natural', 'faithful', 'literal', 'academic', 'plain_japanese')",
            name="ck_style_translationstyle",
        ),
        sa.ForeignKeyConstraint(["selection_id"], ["text_selections.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_translations_input_hash"), "translations", ["input_hash"], unique=False
    )
    op.create_index("ix_translations_selection", "translations", ["selection_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_translations_selection", table_name="translations")
    op.drop_index(op.f("ix_translations_input_hash"), table_name="translations")
    op.drop_table("translations")
    op.drop_index("ix_equation_symbols_equation", table_name="equation_symbols")
    op.drop_table("equation_symbols")
    op.drop_index("ix_derivation_steps_from", table_name="derivation_steps")
    op.drop_table("derivation_steps")
    op.drop_index("ix_selections_user_paper", table_name="text_selections")
    op.drop_table("text_selections")
    op.drop_index("ix_saved_user_status", table_name="saved_papers")
    op.drop_table("saved_papers")
    op.drop_index(op.f("ix_paper_relations_target_paper_id"), table_name="paper_relations")
    op.drop_index(op.f("ix_paper_relations_source_paper_id"), table_name="paper_relations")
    op.drop_table("paper_relations")
    op.drop_index("ix_paper_identifiers_paper", table_name="paper_identifiers")
    op.drop_table("paper_identifiers")
    op.drop_table("paper_fields")
    op.drop_index("ix_impressions_user_shown_at", table_name="impressions")
    op.drop_index("ix_impressions_user_paper", table_name="impressions")
    op.drop_table("impressions")
    op.drop_index("ix_expressions_user", table_name="expression_cards")
    op.drop_table("expression_cards")
    op.drop_index("ix_equations_paper", table_name="equations")
    op.drop_table("equations")
    op.drop_table("collection_items")
    op.drop_index("ix_actions_user_created", table_name="actions")
    op.drop_table("actions")
    op.drop_index("ix_abstract_segments_paper", table_name="abstract_segments")
    op.drop_table("abstract_segments")
    op.drop_table("user_settings")
    op.drop_index("ix_review_events_entity", table_name="review_events")
    op.drop_table("review_events")
    op.drop_index("ix_papers_primary_field_year", table_name="papers")
    op.drop_index(op.f("ix_papers_normalized_title"), table_name="papers")
    op.drop_index(op.f("ix_papers_canonical_id"), table_name="papers")
    op.drop_table("papers")
    op.drop_index(op.f("ix_interests_user_id"), table_name="interests")
    op.drop_table("interests")
    op.drop_index(op.f("ix_collections_user_id"), table_name="collections")
    op.drop_table("collections")
    op.drop_index(op.f("ix_canvas_positions_user_id"), table_name="canvas_positions")
    op.drop_table("canvas_positions")
    op.drop_table("users")
    op.drop_table("math_cards")
    op.drop_table("fields")
    op.drop_index(op.f("ix_embeddings_entity_id"), table_name="embeddings")
    op.drop_table("embeddings")
    op.drop_index("ix_audit_log_kind_created", table_name="audit_log")
    op.drop_table("audit_log")
    # ### end Alembic commands ###
